name: Build Web App
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  API-Analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.X_ENV }}" > .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          env: "${{ secrets.X_ENV }}"
      - run: npm i --save-dev supertest mocha chai @babel/cli @babel/core @babel/node @babel/register @babel/preset-env 
      - run: npm i dotenv
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
