name: Build Web App
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  API-Analysis:
    runs-on: ubuntu-latest
    environment: ENV_FILE
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v3
      - name : Run some customized action
        env :
            a : ${{ secrets.X_ENV }}
        run : |
            echo $a 
            echo $b
            echo $c
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --save-dev supertest mocha chai @babel/cli @babel/core @babel/node @babel/register @babel/preset-env 
      - run: npm i dotenv
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "${{ secrets.X_ENV}}" > .env
      - run: npm test
      
  
